name: Frontend Deployment

on:
   workflow_dispatch: 
   push:
    branches: [ main ]
    paths:
      - 'website-frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WEBSITE-FRONTEND

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Docker Image
        run: |
          docker build -t intuteai/website-frontend:latest .

      - name: Push Frontend Docker Image
        run: |
          docker push intuteai/website-frontend:latest

      - name: SSH to VPS and Deploy Frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/website-docker
            docker-compose pull frontend
            docker-compose up -d frontend
